name: "jeandle-llvm check"

on:
  pull_request_target:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  test:
    name: "jeandle-llvm test"
    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        include:
          - arch: x64
            target: X86
            runs-on: ubuntu-22.04
          - arch: aarch64
            target: AArch64
            runs-on: ubuntu-22.04-arm

    steps:
      - name: 'checkout the source code'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 1

      - name: build and test
        run : |
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -DLLVM_TARGETS_TO_BUILD=${{ matrix.target }} -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_DYLIB_COMPONENTS=all ../llvm
          make check-llvm -j $[$(nproc)/2]

  clang-format:
    name: "clang-format check"
    runs-on: ubuntu-22.04
    steps:
      - name: 'checkout the source code'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 1
      - name: clang-format
        run : |
          git remote add jeandle-main https://github.com/jeandle/jeandle-llvm.git
          git fetch --depth=1 jeandle-main
          sudo apt-get install -y clang-format
          git clang-format jeandle-main/main
